language: node_js
install:
  - yarn
cache:
  directories:
    - node_modules
node_js:
  - "14"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - cp qmui.config.js ../qmui.config.js
  - yarn install
script:
  - gulp initProject
  - gulp list
  - gulp sass
  - gulp include
  - gulp clean
  - gulp merge
